name: hypseek
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - cairo=1.18.0
  - certifi=2025.8.3
  - comm=0.2.2
  - conda-pack=0.8.1
  - debugpy=1.8.14
  - expat=2.7.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - icu=73.2
  - importlib-metadata=8.7.0
  - ipykernel=6.29.5
  - jq=1.7.1
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.40
  - libedit=3.1.20191231
  - libexpat=2.7.0
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libglib=2.80.2
  - libgomp=14.2.0
  - libiconv=1.18
  - libnsl=2.0.1
  - libpng=1.6.43
  - libsodium=1.0.20
  - libsqlite=3.46.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libuuid=2.38.1
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxml2=2.12.7
  - libzlib=1.2.13
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - oniguruma=6.9.10
  - openbabel=3.1.1
  - openssl=3.5.2
  - pcre2=10.43
  - pip=25.0
  - pixman=0.44.2
  - pthread-stubs=0.4
  - python=3.11.8
  - python_abi=3.11
  - pyzmq=27.0.0
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tornado=6.5.1
  - wheel=0.45.1
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xorgproto=2024.1
  - xorg-xproto=7.0.31
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.2.13
  - pip:
      - absl-py==2.2.2
      - annotated-types==0.7.0
      - anyio==4.9.0
      - asttokens==3.0.0
      - attrs==25.3.0
      - bel-resources==0.0.3
      - bio==1.8.0
      - biopandas==0.5.1
      - biopython==1.85
      - bioregistry==0.12.13
      - biothings-client==0.4.1
      - cairocffi==1.7.1
      - cairosvg==2.8.2
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - click-plugins==1.1.1
      - contourpy==1.3.2
      - cssselect2==0.8.0
      - curies==0.10.19
      - cycler==0.12.1
      - decorator==5.2.1
      - defusedxml==0.7.1
      - dnspython==2.7.0
      - docker-pycreds==0.4.0
      - email-validator==2.2.0
      - executing==2.2.0
      - filelock==3.13.1
      - fonttools==4.58.0
      - fsspec==2024.6.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - gprofiler-official==1.0.0
      - greenlet==3.2.2
      - grpcio==1.71.0
      - h11==0.16.0
      - hf-xet==1.1.5rc1
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.30.2
      - humanize==4.12.3
      - idna==3.10
      - ipython==9.3.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jinja2==3.1.4
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2025.4.1
      - kiwisolver==1.4.8
      - lmdb==1.6.2
      - loguru==0.7.3
      - looseversion==1.1.2
      - lz4==4.4.4
      - markdown==3.8
      - markupsafe==2.1.5
      - matplotlib==3.10.3
      - matplotlib-inline==0.1.7
      - ml-collections==1.1.0
      - mmtf-python==1.1.3
      - more-click==0.1.2
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multisplitby==0.0.1
      - mygene==3.2.2
      - networkx==3.3
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-ml-py==12.570.86
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nvtx-cu11==11.8.86
      - nvitop==1.5.0
      - opentelemetry-api==1.34.1
      - opentelemetry-sdk==1.34.1
      - opentelemetry-semantic-conventions==0.55b1
      - packaging==25.0
      - pandas==2.2.3
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==11.0.0
      - platformdirs==4.3.7
      - pooch==1.8.2
      - prompt-toolkit==3.0.51
      - protobuf==6.30.2
      - psutil==7.0.0
      - psycopg2-binary==2.9.10
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pybel==0.15.5
      - pycparser==2.22
      - pydantic==2.11.3
      - pydantic-core==2.33.1
      - pygments==2.19.1
      - pyparsing==3.2.3
      - pystow==0.7.0
      - python-dateutil==2.9.0.post0
      - pytrie==0.4.0
      - pytz==2025.2
      - pyyaml==6.0.2
      - ratelimit==2.2.1
      - rdkit==2023.9.6
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - requests-file==2.1.0
      - rpds-py==0.24.0
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - seaborn==0.13.2
      - sentry-sdk==2.27.0
      - setproctitle==1.3.5
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - sqlalchemy==2.0.41
      - stack-data==0.6.3
      - sympy==1.13.3
      - tabulate==0.9.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - tokenizers==0.21.1
      - torch==2.7.0+cu118
      - torchaudio==2.7.0+cu118
      - torchsort==0.1.10
      - torchvision==0.22.0+cu118
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.51.3
      - triton==3.3.0
      - typing-extensions==4.12.2
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - unicore==0.0.1
      - urllib3==2.4.0
      - wandb==0.19.10
      - wcwidth==0.2.13
      - webencodings==0.5.1
      - werkzeug==3.1.3
      - zstandard==0.23.0
